<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_termsOfUse</name>
   <tag></tag>
   <elementGuidId>3e0da8ee-4539-49ed-8d37-319653985b44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[href=&quot;/terms-of-use/&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
