<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_sampleFooter</name>
   <tag></tag>
   <elementGuidId>09975abf-6f62-4e21-9c17-9f5393673875</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.simple-footer</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
