<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_cartLabel</name>
   <tag></tag>
   <elementGuidId>6852e735-6708-4c21-a596-c2a86eb34bcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.cart-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
