<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_counterCheckIn</name>
   <tag></tag>
   <elementGuidId>be6d9a3e-bf19-431f-9322-cc297357c8c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>href=&quot;/Counter-Check-In/&quot;</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
