<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_tagsForm</name>
   <tag></tag>
   <elementGuidId>44d91bbf-ff05-4af7-ac28-7e4c3b086b81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>href=&quot;/Tags-Forms/&quot;</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
