<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_leave-feedback-form</name>
   <tag></tag>
   <elementGuidId>1bf7e6f0-2c93-422b-95d3-0d3df43fb8a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leave-feedback-form</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
