<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_loginHeader</name>
   <tag></tag>
   <elementGuidId>f6f19c28-5ac3-4be3-a953-4dd2413aa25a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;login-page&quot;]/div/div[1]/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//*[@id=&quot;login-page&quot;]/div/div[1]/div/h2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
