<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_recaptcha</name>
   <tag></tag>
   <elementGuidId>a738d875-091b-4402-9417-9023e5fe5475</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.recaptcha-checkbox</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
