<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_checkoutHeader</name>
   <tag></tag>
   <elementGuidId>95ef651d-02e1-4596-ba28-19891eeb4295</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.heading</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
