<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_shopiingTableSku</name>
   <tag></tag>
   <elementGuidId>c8f594dc-eb72-4958-8c75-1e537339f6d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.sku-number</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
