<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div.accountDropDown</name>
   <tag></tag>
   <elementGuidId>ffd4f570-d21c-423b-8bd6-b4262f7d9824</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.account-dropdown</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
