<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_headerEmail</name>
   <tag></tag>
   <elementGuidId>238f088a-8511-420a-aaa6-60e4b9fe5fa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#headerEmail</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
