<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_customerServicesArea</name>
   <tag></tag>
   <elementGuidId>0570a979-d457-425f-a319-332e9f8a32e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.service-area</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
