<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_infoHolder</name>
   <tag></tag>
   <elementGuidId>e3c7fb70-e1ef-4382-a4ed-a2db05efd1e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.info-holder</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
