<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_emailSubscribe</name>
   <tag></tag>
   <elementGuidId>7a4e0eae-c391-4798-8cfa-e5a954e4c5c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#newsletterEmail</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
