<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_contactInfo</name>
   <tag></tag>
   <elementGuidId>864cd563-29dc-4385-bcc1-cb41320415f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.contact-info</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
