<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_successMessage</name>
   <tag></tag>
   <elementGuidId>bbef6474-9596-45ca-8864-3cc6f546c69b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.success-message</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
