<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PoNoDiv</name>
   <tag></tag>
   <elementGuidId>8047252e-4607-4841-a681-3fdc04cf440a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.po-number-container</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
