<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_paymentMethodPo</name>
   <tag></tag>
   <elementGuidId>029a765d-8c20-48cc-9e2a-ddf7f2aaf200</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#po</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
