<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_paymentMethodComment</name>
   <tag></tag>
   <elementGuidId>ceac4b9c-a77c-4477-9e43-d294f1ff6b48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comments</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
