<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_searchAutocompleteBox</name>
   <tag></tag>
   <elementGuidId>23115a7f-f727-468f-b09e-0d96ca29483e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.search-autocomplete</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
