<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_descHeader</name>
   <tag></tag>
   <elementGuidId>39dd1f9f-949f-4fd4-a944-80dfda0345df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.description-header</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
