<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div.pagenationSection</name>
   <tag></tag>
   <elementGuidId>6ea6e6ad-66d8-4859-a60c-84ef68d7062e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pagination-section</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
