<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_priceRange</name>
   <tag></tag>
   <elementGuidId>41394b45-2b6d-406c-a963-4ccdaaabf1d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.price-container</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>div.price-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
