<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_productName</name>
   <tag></tag>
   <elementGuidId>370f97de-2901-4583-95ed-d22873b790cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.product-title</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
