<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_availability</name>
   <tag></tag>
   <elementGuidId>5546b5fc-a07f-46c4-b331-617af2fe4dfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.availability</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
