<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_headerSearch</name>
   <tag></tag>
   <elementGuidId>51e04427-8932-4ed6-9456-6fed74b75122</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div#header-search</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
