<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_myAccount</name>
   <tag></tag>
   <elementGuidId>7bc98e0d-f266-4a04-8a36-94b9a60a07f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li#my-account</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
